### ISSUE TITLE
It seems like ghcr.io/loft-sh/devspace-containers/java-gradle:7-jdk8-slim is still using jdk17

### ISSUE THREAD

**Issue by benlei-gfm** [loft-sh/devspace-containers#10]
With:

```
dev:
  app:
    # Search for the container that runs this image
    imageSelector: ${IMAGE}
    # Replace the container image with this dev-optimized image (allows to skip image building during development)
    devImage: ghcr.io/loft-sh/devspace-containers/java-gradle:7-jdk8-slim
```

This is what shows when I describe the pod:

```
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  88s   default-scheduler  Successfully assigned awesometown/app-devspace-7b785f7949-h5855 to ip-10-90-2-21.ec2.internal
  Normal  Pulling    87s   kubelet            Pulling image "ghcr.io/loft-sh/devspace-containers/java-gradle:7-jdk8-slim"
  Normal  Pulled     63s   kubelet            Successfully pulled image "ghcr.io/loft-sh/devspace-containers/java-gradle:7-jdk8-slim" in 24.168614216s
  Normal  Created    62s   kubelet            Created container container-0
  Normal  Started    62s   kubelet            Started container container-0
```

But when I try to get the java version from within the pod it shows:

```
devspace ./spring-auditor # java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
```
