### ISSUE TITLE
Missing containers

### ISSUE THREAD

**Issue by pwillis-eiq** [loft-sh/devspace-containers#18]
At least for the Python containers, some containers are missing from remote registries.

Container `loftsh/python:3.9-alpine` exists, but `docker pull loftsh/python:3.10-alpine` does not.

Trying to pull them from `ghcr.io/loft-sh/devspace-containers/python:alpine` doesn't work at all, even though that's the example used in the default `devspace.yaml`

**Comment by alexandradragodan** [comment]
Hey, @pwillis-eiq 👋 
Thanks for reporting this issue! 

Someone in our team will get back to you soon! 
Stay tuned 💯

**Comment by carlmontanari** [comment]
👋 

#19 should sort having the other versions updated. can you link where this `ghcr.io/loft-sh/devspace-containers/python:alpine` is in the docs so I can adjust?

thanks

**Comment by pwillis-eiq** [comment]
@carlmontanari when I run `devspace init` and select Python as the programming language, then all the rest of the defaults, part of the configuration includes this:

```
# This is a list of `dev` containers that are based on the containers created by your deployments
dev:
  app:
    # Search for the container that runs this image
    imageSelector: username/app
    # Replace the container image with this dev-optimized image (allows to skip image building during development)
    devImage: ghcr.io/loft-sh/devspace-containers/python:3-alpine
```

^ technically it says "python:3-alpine" instead of "python:alpine", but I expected to be able to pull the other python 3 tags using that url, and it seems like they're not available there


```
$ docker pull ghcr.io/loft-sh/devspace-containers/python:3.9-alpine
3.9-alpine: Pulling from loft-sh/devspace-containers/python
8921db27df28: Pull complete
3fd9832a787c: Extracting  32.77kB/622.9kB
364673216b3b: Downloading  122.9kB/11.91MB
6d9ba5708eb7: Download complete
f2c1e22b0c5a: Waiting
0fd8d52a2dac: Download complete
bf74ef50a00e: Waiting
955ef764a920: Waiting
$ docker pull ghcr.io/loft-sh/devspace-containers/python:3.10lpine
Error response from daemon: manifest unknown
```
