### ISSUE TITLE
Allow non-root users access to /app in dev container images

### ISSUE THREAD

**Issue by dicki** [loft-sh/devspace-containers#24]
Is it possible to get this issue addressed? https://github.com/devspace-sh/devspace/issues/2590

All our applications by default run as a non-root user and we always have to add the following config to our devspace file, because the dev images don't allow non-root users access to the `/app` directory within the container image.

```yaml
...
dev:
  app:
    patches:
      - op: replace
        path: spec.containers[0].securityContext.runAsUser
        value: 0
      - op: replace
        path: spec.containers[0].securityContext.runAsGroup
        value: 0
      - op: replace
        path: spec.containers[0].securityContext.runAsNonRoot
        value: false
      - op: replace
        path: spec.containers[0].securityContext.fsGroup
        value: 0
...
```

This is not a serious issue, but adds some bloat to our devspace files and comes up every now and then in discussions.

I have the fix any thought, otherwise I would probably do a PR to assist in fixing this.
